docs: update documentation to support 10.0 release
cypress-io/code-coverage pull request #549
Opened 2022-02-03 23:17 UTC by jordanpowell88

This PR adds documentation to support the `10.0` release

Closes UDX-112

2022-02-03 23:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/code-coverage?pullRequest=549) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/code-coverage?pullRequest=549) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/code-coverage?pullRequest=549) it.</sub>

2022-02-07 16:01 UTC, elylucas requested changes

2022-02-07 16:01 UTC, elylucas commented on README.md
> +### Prior to 10.0
When referencing the version, we should specify its Cypress so they don't get confused what needs to be v10 (Cypress or the plugin), so maybe here and elsewhere "### Prior to Cypress 10.0"

2022-02-07 18:31 UTC, jordanpowell88 commented on README.md
> +### Prior to 10.0
Great point on clarifying this. That change can be found here https://github.com/cypress-io/code-coverage/pull/549/commits/f80d043fee9c4ac8fd524d7c3f9056d9df014e9a

2022-02-07 20:35 UTC, elylucas approved these changes

2022-02-07 20:37 UTC, merged